language: java
before_install:
  - chmod +x mvnw
addons:
 sonarcloud:
    organization: "praxis_integrador"
    token:
      secure: SONAR_TOKEN
script:
  - "mvn test"
  #-  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
deploy:
  provider: heroku
  api_key:
    master: 55f05f85-8553-47a3-9b6e-b344cc5da044
    test: c2c4954e-58e8-4839-96c3-1536a132abc9
  app:
    master: integrador2018
    test: integrador2018apitest
  on:
    repo: jdvallejor/integrador2018api